# Generated by Django 4.0.4 on 2022-04-13 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('date', models.DateField()),
                ('dept', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('msg', models.CharField(max_length=300)),
            ],
        ),
    ]
