# Generated by Django 4.0.4 on 2022-04-13 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthCenter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='dept',
            field=models.CharField(choices=[('Gerneral Helth', 'Gerneral Helth'), ('Cardiology', 'Cardiology'), ('Dental', 'Dental'), ('Dental', 'Dental'), ('Medical Research', 'Medical Research')], max_length=100),
        ),
    ]
